export class Instruments {
  playerName: string | undefined;
  tas: number | undefined;
  ias: number | undefined;
  altitude: number | undefined;
  verticalSpeed: number | undefined;
  pitch: number | undefined;
  throttle: number | undefined;
  climbAngle: number | undefined;
  radiator: number | undefined;
  valid: boolean | undefined;
  bearing: number | undefined;
  bearingReading: string | undefined;
  propPitch: number | undefined;
  manifoldPressure: number | undefined;
  oilTemp: number | undefined;
  waterTemp: number | undefined;
  engineTemp: number | undefined;
  killed: boolean | undefined;
}
